services:
  kodi-repo-server:
    image: ghcr.io/m4rc-xx/kodi-repo-server-docker:latest
    container_name: kodi-repo-server
    ports:
      - "80:80"
    volumes:
      - /home/pi/kodi-repository/input:/app/input
      - /home/pi/kodi-repository/addons:/app/addons
      - /home/pi/kodi-repository/web:/app/web
      - /home/pi/kodi-repository/zips:/app/zips
    user: "${UID}:${GID}"
    restart: unless-stopped